# interactive mode flags
I_REWRITE = 0
I_UNFLATTEN = 0
I_JOIN = 0

# print verbosity flags
P_MAIN = 1
P_STATES = 1
P_SUCCESSORS = 0
P_UNFLATTENED = 0
P_RULES = 0
P_COSTS = 0
P_STATE_PATH = 1
P_JOIN_GEN = 0
P_JOIN_VERIF = 0
P_SUCCESS_PATH = 1
P_STATS = 1

R_CHECK = 1